name: Build reviewable container
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  container:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t print-approval-system:${{ github.sha }} .
      - run: docker save print-approval-system:${{ github.sha }} | gzip > print-approval-system-container.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: print-approval-system-container-${{ github.sha }}
          path: print-approval-system-container.tar.gz
          retention-days: 7
